function Help()
	print("--telescope--")
	print("<space>pf: fuzzyfind")
	print("control p: git file")
	print("<space>ps: grep line")

	print("--harpoon--")
	print("<spcae>a: add file")
	print("C-h: file 1, C-t: file 2, C-n: file 3, C-s: file 4")

	print("--terminal--") -- damn the AI autocompleted this thing by itself
	print("alt+v: vertical")
	print("alt+h: horizontal")
	print("alt+f: float")
	print("control+x: exit terminal mode")

	print("--aerial--")
	print("{: AerialPrev")
	print("}: AerialNext")
	print("control+a: toggle aerial")

	print("--tabby--")
	print("<space>ta: new tab")
	print("<space>tc: close tab")
	print("<space>to: close all tab besides this")
	print("<space>tn: next tab")
	print("<space>tp: previous tab")
	print("<space>tmp: move tab")
	print("<space>tmn: move tab")

	print("--codeium--")
	print("accept: control + g")
	print("cycle: control + ;, control + ,")
	print("clear suggestion: control + x")
	print("code window: <space>mm")

	print("--LSP--")
	print("<space>gd: goto definition")
	print("<space>xf: code action")

	print("--single packages--")
	print("esc: clear marks")
	print("fugitive: <spcae>gs")
	print("swap windows: <space>w")
	print("tagbar: <space>tb")
	print("format: <space>f")
	print("netrw: <spcae>pv")
	print("undo tree: <space>u")
	print("lazygit: <space>gg")
	print("neotree: <spcae>nt")
	print("searchbox: <space>se")
	print("leap: S<search item>, s<search item>")
	print("nnn: <spcae>nn")
	print("trouble: <space>xx")

	print("--misc commands--")
	print("colorutils: :Colorutils")
	print("rename this object: :IncRename")
	print("shift window: :WinShift")
end

